spring:
  redis:
    host: out-redis-39-105-65-104.redis.rds.aliyuncs.com
    port: 6379
    password: zjj:Sunny929
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
server:
  url: http://192.168.1.104:20080/addr/
  port: 20090
netty:
  udp:
    port: 20000
logging:
  level:
    com.zjj: debug
